type: object
additionalProperties: false
properties:
  cuddles:
    description: >
      Cuddle Monkey uses CloudWatch scheduled events to ping the target API and keep it warm.  This stanza configures that activity.
    type: object
    additionalProperties: false
    required: [interval]
    properties:
      interval:
        description: The frequency of the pings against the target API, given in minutes.
        type: integer
        minimum: 1
        maximum: 3153600000

  tags:
    description: >
      Optional tags attached to the CloudWatch resources to make it easier to track and monitor. These tags are applied in addition to the ones that are part of the global Sky configuration, so there is no need to repeat.
    type: array
    minItems: 1
    uniqueItems: true
    items:
      type: object
      additionalProperties: false
      required: [ Key, Value ]
      properties:
        Key:
          description: >
            Name of tag. This is an arbitrary string you provide to track
            resource groupings of interest.
          type: string
        Value:
          description: >
            The value that goes with the matching tag type. This is an
            aribitrary string you provide to track resource groupings of
            interest.
          type: string
