{{#each targetGroups}}
MixinCuddleMonkey{{@root.stackName}}{{@key}}:
  Type: "AWS::Events::Rule"
  Properties:
    Description: Preheater for the {{@root.stackName}} API
    ScheduleExpression: {{@root.interval}}
    State: ENABLED
    Targets:
      {{#each targets}}
      - Id: {{.}}
        Arn: {"Fn::GetAtt": [{{.}}, "Arn"]}
        Input: '{"source": "cuddle-monkey"}'
      {{/each}}

{{#each targets}}
MixinCM{{.}}Role:
  DependsOn:
    - MixinCuddleMonkey{{@root.stackName}}{{@../key}}
  Type: "AWS::Lambda::Permission"
  Properties:
    Action: "lambda:InvokeFunction"
    FunctionName:
      "Fn::GetAtt": [{{.}}, "Arn"]
    Principal: events.amazonaws.com
    SourceArn:
      "Fn::GetAtt": [MixinCuddleMonkey{{@root.stackName}}{{@../key}}, "Arn"]
{{/each}}
{{/each}}
