{{#each targetGroups}}
MixinCuddleMonkey{{@root.stackName}}{{@key}}:
  Type: "AWS::Events::Rule"
  Properties:
    Description: Preheater for the {{@root.stackName}} API
    ScheduleExpression: {{@root.interval}}
    State: ENABLED
    Targets:
      {{#each targets}}
      - Id: {{id}}
        Arn: {{arn}}
        Input: '{"source": "cuddle-monkey"}'
      {{/each}}

{{#each targets}}
MixinCM{{id}}Role:
  DependsOn:
    - MixinCuddleMonkey{{@root.stackName}}{{@../key}}
  Type: "AWS::Lambda::Permission"
  Properties:
    Action: "lambda:InvokeFunction"
    FunctionName: {{arn}}
    Principal: events.amazonaws.com
    SourceArn:
      "Fn::GetAtt": [MixinCuddleMonkey{{@root.stackName}}{{@../key}}, "Arn"]
{{/each}}
{{/each}}
